### ISSUE TITLE
Local llm support

### ISSUE THREAD

**Issue by killind-dev** [entropy-research/Devon#15]
This issue requires adding ollama and supported models with prompts as an alternative model choice.

Would also be nice to add default model selection to the devon command with `devon set-default`

**Comment by antoninoLorenzo** [comment]
I looked inside the source code and it seems like the integration of Ollama is possible by modifying the following modules:
- devon_agent/model.py requires a configurable OllamaModel interface;
- devon_agent/agent.py requires TaskAgent to enable configuration to chose what model to use when `self.current_model` is set inside predict method;
- devon_agent/agent.py requires PlanningAgent to enable configuration to chose what model to use in `__init__`;
- the current start up command `devon` should accept parameters to tell what model to use.

Other than that there are other places that require slight modification (ex. server.py) and the prompts need to be fine-tuned for different models.

To be future-proof the OllamaModel interface should be designed to accept Modelfile configurations, even if in a first iteration it isn't needed.

Those are just my considerations upon reviewing some of the source code, I am looking to contribute but I think the feature should be approved and planned before.

**Comment by killind-dev** [comment]
Hey, yeah so it looks like ollama is really usable with this, I just added some code to use litellm. After I have that worked out @antoninoLorenzo would love for you to take a look and see how ollama can fit in better (I'll be adding a basic implementation but it can definitely be made better in a lot of ways)

@cocobeach shoutout, appreciate the heads up on ollama!!

**Comment by antoninoLorenzo** [comment]
@killind-dev if you make a branch to work on the ollama integration I would really enjoy to fork it, also tell me if you already have a plan on how to integrate it.

**Comment by killind-dev** [comment]
Yep, I'll make a branch for it in a couple hours. Thanks!

**Comment by atljoseph** [comment]
Interested in this too. Running Ollama locally with <= 70b models.

**Comment by killind-dev** [comment]
@antoninoLorenzo I just merged multi model support and added ollama. I just made the `ollama-support` branch for you to fork! I will also begin working on supporting local models, but you can take a look at the devon_agent/agents/default folder to get familiar with the new `litellm` implementation.

**Comment by Qarqor5555555** [comment]
Adding Olama and the free models will enrich Devon and will benefit more people

**Comment by antoninoLorenzo** [comment]
@killind-dev Yes, I took a look at the code and I have started working on a module `ollama_prompts.py` in the `agents/default` folder and I am taking as reference `openai_prompts.py`.
