### ISSUE TITLE
Running into Claude limits

### ISSUE THREAD

**Issue by DanielAndrews43** [entropy-research/Devon#16]
> Error: Error code: 429 - {'type': 'error', 'error': {'type': 'rate_limit_error', 'message': 'Number of request tokens has exceeded your per-minute rate limit (https://docs.anthropic.com/claude/reference/rate-limits); see the response headers for current usage. Please reduce the prompt length or the maximum tokens requested, or try again later. You may also contact sales at https://www.anthropic.com/contact-sales to discuss your options for a rate limit increase.'}}

**Comment by Mihir1003** [comment]
There's not much we can do in the short term. The best course of action would be adding support for OpenAI and Groq which have more generous rate limits. If you spend more than a certain amount and wait for 7 days they increase it for you. 
Thanks for pointing it out!

**Comment by DanielAndrews43** [comment]
Is there an easy way to add in a delay and just have it run more slowly? E.g. wait 60 seconds if we get near the limit. Maybe a CLI flag for max number of tokens per minute? If we spread the requests from 11:01pm to different minutes I think we'd be fine here

<img width="1169" alt="image" src="https://github.com/entropy-research/Devon/assets/6037887/a3c0cbc2-dfdf-4867-b9cb-6cfc53b23b76">

**Comment by Mihir1003** [comment]
Thanks, good idea! yeah I can add that

**Comment by Mihir1003** [comment]
should be resolved! Let me know if it persists

**Comment by tadeodonegana** [comment]
Hi, i am running into the same error running the last version.

`Error: AnthropicException - {"type":"error","error":{"type":"rate_limit_error","message":"Number of request tokens has exceeded your per-minute rate limit (https://docs.anthropic.com/en/api/rate-limits); see the response headers for current usage. Please reduce the prompt length or the maximum tokens requested, or try again later. You may also contact sales at https://www.anthropic.com/contact-sales to discuss your options for a rate limit increase."}}`

**Comment by ObjectJosh** [comment]
Hi @tadeodonegana sometimes it first shows this rate limit error right before it runs out of credits. Have you checked that you still have some Anthropic credits? If so, then this isn't the issue and we can debug further
