### ISSUE TITLE
OpenAI Support

### ISSUE THREAD

**Issue by Mihir1003** [entropy-research/Devon#18]
Add support for OpenAI models.

**Comment by ObjectJosh** [comment]
gpt4o!
Would love to implement vision + voice once it comes out: https://x.com/OpenAI/status/1790130708612088054

**Comment by killind-dev** [comment]
GPT4-o support coming in today. Will also be adding voice support in a few days.

**Comment by killind-dev** [comment]
GPT4-o support is integrated. closing.

**Comment by AlysonBasilio** [comment]
@killind-dev Any instruction on how to use it? I tried to reinstall the agent here but it didn't seem to get the new version, it keeps asking me for the anthropic api key...
