### ISSUE TITLE
Stuck on initializing

### ISSUE THREAD

**Issue by mberman84** [entropy-research/Devon#19]
I installed everything and when I ran the command "devon" it gets stuck on initailizing.

**Comment by ObjectJosh** [comment]
@mberman84 Hey thanks for raising this issue! Currently it doesn't handle all errors well so it might have crashed somewhere along the way. Are there any logs above the "Initializing..." UI?

**Comment by mberman84** [comment]
@ObjectJosh no logs

**Comment by ObjectJosh** [comment]
@mberman84 Hm, interesting. What OS are you on? And does it happen consistently (it hasn't been able to respond after restarting?)

**Comment by businistry** [comment]
I am experiencing the same thing on Mac Pro M3

**Comment by killind-dev** [comment]
Ok, theres going to be a big refactor we are packaging today that should fix the hanging. Will also include openai support. @mberman84 @businistry

**Comment by SuperMohit** [comment]
Same issue on Macbook Pro M3

**Comment by killind-dev** [comment]
Interesting. Another person tried it and had an issue on M3. Taking a dive tomorrow.

**Comment by killind-dev** [comment]
Hey @mberman84 did it end up working for you? We just pushed a new version that seems to be better.

**Comment by 1of13** [comment]
I'm on an M3 Mac. To get it to work, I deleted the "devon-agent" in "/Users/your_home_directory/.local/pipx/venvs/devon-agent" and then reinstalled it.

**Comment by killind-dev** [comment]
Hey all, heres a couple things you can try:

1) uninstall via pipx and reinstall the latest version
2) upgrade nodejs version to 22, I tested this yesterday (I found a failure in nodejs 18 that we haven't quite solved yet)
3) run in debug mode, that may help us understand whats going on

@drupalshift @SuperMohit

**Comment by akiradev0x** [comment]
awesome! @businistry glad to hear it. I think for now, we can close this issue.

**Comment by dada-mhmd** [comment]
for me it stuck like this. i uninstalled everthing then install again, updated npm and node. 
![devon](https://github.com/entropy-research/Devon/assets/49029081/102f19fb-8a4c-40c5-bea3-2e7a15065082)
