### ISSUE TITLE
Compatibly issue, Windows 11 

### ISSUE THREAD

**Issue by sonicino2** [entropy-research/Devon#22]
Hello, yeah, I got this error after running pipx install devon_agent:

(env) PS C:\Users\sonic\Downloads\Devon> pipx install devon_agent
Fatal error from pip prevented installation. Full pip output in file:
    C:\Users\sonic\.local\pipx\logs\cmd_2024-05-15_23.37.05_pip_errors.log       

Some possibly relevant errors from pip install:
    ERROR: Ignored the following versions that require a different python version: 0.0.1 Requires-Python <4.0,>=3.10; 0.0.2 Requires-Python <4.0,>=3.10; 0.0.3 Requires-Python <4.0,>=3.10; 0.0.4 Requires-Python <4.0,>=3.10; 0.0.5 Requires-Python <4.0,>=3.10; 0.0.6 Requires-Python <4.0,>=3.10; 0.0.7 Requires-Python <4.0,>=3.10; 0.1.0 Requires-Python <4.0,>=3.10; 0.1.1 Requires-Python <4.0,>=3.10; 0.1.2 Requires-Python <4.0,>=3.10; 0.1.3 Requires-Python <4.0,>=3.10; 0.1.4 Requires-Python <4.0,>=3.10; 0.1.5 Requires-Python <4.0,>=3.10; 0.1.6 Requires-Python <4.0,>=3.10
    ERROR: Could not find a version that satisfies the requirement devon-agent (from versions: none)
    ERROR: No matching distribution found for devon-agent

Error installing devon-agent.

Any help, is much appreciated.

**Comment by ObjectJosh** [comment]
Hey @sonicino2, to my knowledge we are currently working on adding support for Windows. Sorry about the inconvenience! I will ping you once we release a version that supports it 👍

**Comment by emosGambler** [comment]
Is there any update?

**Comment by emosGambler** [comment]
Anything? :). What is there to be done exactly?
