### ISSUE TITLE
I hit rate limit using Claude 3

### ISSUE THREAD

**Issue by PierrunoYT** [entropy-research/Devon#23]
I hit rate limit using Claude 3

**Comment by killind-dev** [comment]
Hey! Thanks for opening this. We are adding gpt4-o and ollama support today.

**Comment by PierrunoYT** [comment]
Okay. Can you make a new release or how can I know when it's updated and can update it?

**Comment by killind-dev** [comment]
@PierrunoYT just merged a branch that has openai support. Will be out tomorrow!

**Comment by killind-dev** [comment]
@PierrunoYT Just pushed openai support! Happy coding! Closing this issue.
