### ISSUE TITLE
Just wanna say thank you

### ISSUE THREAD

**Issue by andr0s** [entropy-research/Devon#30]
Thank you for choosing Anthropic as the primary endpoint. OpenAI has recently been acting as a monster, being hostile towards open source community, proposing hardware spying etc.

I might contribute to Devon in my free time.

Thanks

**Comment by ObjectJosh** [comment]
@andr0s Thanks for your support, would love to have you contribute 👍

**Comment by killind-dev** [comment]
@andr0s Yep!! Also claude is more human. We are wrapping up adding multi model support too which means there will be local models as well supported via ollama!

**Comment by killind-dev** [comment]
closing this issue
