### ISSUE TITLE
It's stuck

### ISSUE THREAD

**Issue by PierrunoYT** [entropy-research/Devon#31]
![grafik](https://github.com/entropy-research/Devon/assets/95778421/9fb1898b-b97e-46d9-b7bb-4a1fb152e0a7)

**Comment by JosueBCe** [comment]
I'm facing the same issue here
![image](https://github.com/entropy-research/Devon/assets/102635770/ee9c0fda-c1b6-4a66-a8cc-14db81dfee98)

**Comment by killind-dev** [comment]
@PierrunoYT @JosueBCe  can you guys run it in debug mode? That would help a lot.

**Comment by killind-dev** [comment]
For reference on how to run in debug mode, see the readme

**Comment by PierrunoYT** [comment]
> @PierrunoYT @JosueBCe can you guys run it in debug mode? That would help a lot.

Try 'devon_agent server --help' for help.


Error: No such option: --model Did you mean --help?

**Comment by killind-dev** [comment]
Cool, thanks. Please install the latest version! Should fix it.

**Comment by killind-dev** [comment]
For context, that error tells me that you have the latest npm version, but not the latest python package which means they are out of sync.

**Comment by dada-mhmd** [comment]
for me i have the same issue when i run it in debug mode it gives me that it is fetching /sessions/clie/events HTTP/1.1 200 OK. but it's stuck..
