### ISSUE TITLE
Exception: Could not find api key on colab

### ISSUE THREAD

**Issue by bitsnaps** [entropy-research/Devon#36]
Hi, I'm getting this error on colab using Groq API, here is a summary of the code:
```python
!sudo apt install pipx -qy

# update Node to v18
%%bash
dpkg --configure -a
sudo apt-get update
sudo apt-get install -y ca-certificates curl gnupg
sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
NODE_MAJOR=18 && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
sudo apt-get update
sudo apt-get install nodejs -qy
```

Install xterm then run the following commands on the terminal
```bash
>python -m venv devon
>source devon/bin/activate

curl -sSL https://raw.githubusercontent.com/entropy-research/Devon/main/install.sh | bash
>pipx ensurepath
>source ~/.bashrc
# re-login and activate "devon" env again, then:

>export GROQ_API_KEY=gsk_...

>devon_agent server

  File "/root/.local/pipx/venvs/devon-agent/lib/python3.10/site-packages/devon_agent/__main__.py", line 23, in server
    raise Exception("Could not find api key")
Exception: Could not find api key
```
There is no `devon` command, it's `devon_agent`, I'm doing something wrong here?

**Comment by cyborgmarina** [comment]
Hmm, if you pass `devon_agent server --model="llama3-70b" --api_key=<groq-key>` it will start the _server_ properly, but you would not be using `devon` cli tool.

If you run `sudo npm install -g devon-tui`, does `devon` command become available?

**Comment by bitsnaps** [comment]
The first command solve the first issue, `devon_agent` is running the server with `uvicorn`on localhost...
Now, I used `tmux` in a new tab to install `devon-tui` with npm globally, and then when running `devon` it keeps asking for the key (either `OPENAI_API_KEY` or `ANTHROPIC_API_KEY`):
```
Please provide an API key using the --api_key option or by setting OPENAI_API_KEY or ANTHROPIC_API_KEY.
```
I tried to provide `--api_key=GROQ_API_KEY` in different ways (e.g. `export GROQ_API_KEY=...; devon`) but it just ignore it!

**Comment by ObjectJosh** [comment]
Hi @bitsnaps the GitHub has Groq implemented, however we haven't updated the package yet. This will happening later this week when we roll out the next update with all the new features (like Groq)! In the meantime, you can clone the repo and run the code locally if you'd like to use Groq before the release

**Comment by ObjectJosh** [comment]
Updated the README. Closing this issue
