### ISSUE TITLE
LM Studio integration

### ISSUE THREAD

**Issue by mrdjohnson** [entropy-research/Devon#38]
👋  I see that local LLMs are on the roadmap, are there any plans for LM Studio as well? Is there anything needed to make adding it easier?

**Comment by killind-dev** [comment]
@mrdjohnson We have a branch with a working ollama integration, but I'm not a big user of LM Studio. However, from what I know its an endpoint right? 

If you have any more context on how you'd like to use it that would be great. Also, I think this may just require a slight change to managing configs.

**Comment by mrdjohnson** [comment]
@killind-dev LM Studio a local platform for using LLMs, it has great support for a lot of huggingface models as well. The server it comes with is open ai api compatible. Like ollama, LM Studio would be an option to use Devon based on local generation.

**Comment by akiradev0x** [comment]
Cool, sounds like [this](https://docs.litellm.ai/docs/providers/custom_openai_proxy) is what we want? Just use the completions function in litellm?

**Comment by akiradev0x** [comment]
@mrdjohnson just merged custom model config support, so in theory this is also covered as long as the endpoint is oai compatible! Will be updating documentation soon with this information. Closing for now.
