### ISSUE TITLE
GROQ not implemented

### ISSUE THREAD

**Issue by nikitaminiaev** [entropy-research/Devon#45]
error:
Please provide an API key using the --api_key option or by setting OPENAI_API_KEY or ANTHROPIC_API_KEY.

The code also shows that the check does not include GROQ_API_KEY

**Comment by ObjectJosh** [comment]
@nikitaminiaev Hi, we will be rolling out the Groq feature in the package in the version coming out this week. Currently it's available if you run the code locally. See https://github.com/entropy-research/Devon/issues/36#issuecomment-2120920146
