### ISSUE TITLE
Multi-Model Config

### ISSUE THREAD

**Issue by akiradev0x** [entropy-research/Devon#47]
Goal here I think is to make sure that we can easily allow users to swap out endpoints, prompts, and models. So to complete this,
we should have a basic config system that captures:

1) default agent name
2) model name

and then, some sort of abstraction that acts as a agent:model:prompt mapping

**Comment by akiradev0x** [comment]
@cyborgmarina feel free to pick this one up!

**Comment by imakecodes** [comment]
This will be awesome, today I was going to task about support to use Ollama instead of OpenAI/other paid options

**Comment by cyborgmarina** [comment]
PR updated here: #53

**Comment by akiradev0x** [comment]
closing, #53 is merged!
