### ISSUE TITLE
Add a way to ignore some folders from scanning

### ISSUE THREAD

**Issue by imakecodes** [entropy-research/Devon#51]
Devon appears to be attempting to read the entire directory, including both 'node_modules' and '.venv' folders. If so, is there a method to create a '.devonignore' file or utilize the existing '.gitignore' file to selectively 'hide' specific content from Devon?

**Comment by ObjectJosh** [comment]
Hey @imakecodes this is a great suggestion! Going ahead and marking it as a good first issue :)

**Comment by Mihir1003** [comment]
Thanks for the idea! I will try to implement this by tomorrow

**Comment by imakecodes** [comment]
@ObjectJosh @Mihir1003 I was taking a look on #53 and make sense to add a "exclude" key on ` .devon.config` file instead of creating a new file for this

**Comment by akiradev0x** [comment]
@imakecodes doing that now!

**Comment by akiradev0x** [comment]
just merged code for this. closing.
