### ISSUE TITLE
Devon sometimes doesnt actually write to files

### ISSUE THREAD

**Issue by Mihir1003** [entropy-research/Devon#54]
In certain scenarios, the agent successfully edits but the changes arent reflected.
Platform: MacOS
Potential causes:
- permissions (can try to create a env where the agents doesn't have any permissions)

(for reference discord: support)

**Comment by akiradev0x** [comment]
This actually is probably happening on empty files. I have replicated that. Will fix right now.

**Comment by akiradev0x** [comment]
fixed
