### ISSUE TITLE
allow Devon's history to be written and read from disk

### ISSUE THREAD

**Issue by emlazzarin** [entropy-research/Devon#56]
Often Devon gets stuck with something — either a loop or other bug — and the only path out is to terminate the process and start over. Ideally, the thought process log, scratchpad, etc. that represents Devon's work could be written to disk so it can resume where it left off should the process need to be terminated.

This could also be useful for running tests, forking Devons, or even collaboration between Devons in the future.

**Comment by akiradev0x** [comment]
@emlazzarin awesome idea, on it. Doing a bug-a-thon tonight and tomorrow, and I'll add this. Thank you for being patient!

**Comment by ObjectJosh** [comment]
Thanks for the feedback! Related #44

**Comment by akiradev0x** [comment]
Just closed this out!
