### ISSUE TITLE
In prompts, "I should perform command2" in CoT but then "command1" is used

### ISSUE THREAD

**Issue by mgsloan** [entropy-research/Devon#57]
https://github.com/entropy-research/Devon/blob/87b0461bc37d045a53acdda5470bcc29a6a72991/devon_agent/prompt.py#L150C1-L158C13

```
  CORRECT:
  <THOUGHT>
  ...thought 1 ...
  ...thought 2 ...
  I should perform command2 in the next step
  </THOUGHT>
  <COMMAND>
  command1 arg1
  </COMMAND>
```

Note `command2` vs `command1`.  While the model gets the gist of it, probably less confusing to it to make this consistent.  This occurs twice in `prompts.py`

**Comment by akiradev0x** [comment]
Oh awesome thank you!!

**Comment by akiradev0x** [comment]
Will take care of this within the next two days. Closing out on a bunch of other tasks right now. @mgsloan

**Comment by akiradev0x** [comment]
This should be fixed now. That prompt file is no longer used and the new ones do not contain the error.
