### ISSUE TITLE
WSL installation errors

### ISSUE THREAD

**Issue by fritol** [entropy-research/Devon#70]
WSL 22.04 ubuntu
during installation this happens
![image](https://github.com/entropy-research/Devon/assets/4304520/e751cc7b-76c2-451e-ba45-5a495eaf2941)

**Comment by werruww** [comment]
not work

**Comment by akiradev0x** [comment]
Yep, ok so this is going to be a longer issue @fritol thanks for opening this

**Comment by akiradev0x** [comment]
I currently am unsure of the cause of why this is happening. First maybe check your node version? Our only known supported versions are 20 or 22 and above

**Comment by fritol** [comment]
i retried the install , it went through

now i get
`file:///usr/local/lib/node_modules/devon-tui/node_modules/meow/index.js:85
                        flag.default = flag.default ?? [];`
whenever i run `devon-tui --help` or any other option

**Comment by akiradev0x** [comment]
Also you should be able to use the ui! with `npx devon-ui`

**Comment by akiradev0x** [comment]
Also if you can, upgrade node version to 22!

**Comment by werruww** [comment]
not work

**Comment by fritol** [comment]
> What node version are you running @fritol ?

`Welcome to Node.js v12.22.9.`

**Comment by fritol** [comment]
> Also if you can, upgrade node version to 22!
upgraded to
` node -v
v22.3.0`

and NOW
without devon reinstall 
` devon-tui` simply starts a session ;)
![image](https://github.com/entropy-research/Devon/assets/4304520/1a3cf40c-bd21-4e3f-a855-5e4c9755735b)

thanks you, ser, @akiradev0x
