### ISSUE TITLE
Devon thinks it cannot creat files

### ISSUE THREAD

**Issue by arjunpredev** [entropy-research/Devon#76]
Devon keeps on responding with `I apologize for the confusion earlier. It seems we can't directly create or access files in this environment,` even though it is able to create these files on my machine.

**Comment by ObjectJosh** [comment]
Hey @arjunpredev is it consistently responding with it? And just to clarify, it actually does end up creating it, correct?

**Comment by arjunpredev** [comment]
Yeah its constantly responding with it even when i till it that it's created the files. It does actually create them.

**Comment by ObjectJosh** [comment]
Ah interesting, i'll look into this thank you for submitting this issue, really appreciate it

**Comment by arjunpredev** [comment]
Is their any permissioning or something I should have enabled on my end?

**Comment by akiradev0x** [comment]
Hm, no permissions required, but it seems like there may be something here going wrong that isn't just the model. What was the path you took to get here?

**Comment by arjunpredev** [comment]
Simply ran npx devon-ui within the folder I installed devon.

**Comment by jmanhype** [comment]
i can attest this is still an issue!

Not sure how kiran is doing so well in his videos

**Comment by jmanhype** [comment]
I SMELL HYPE

**Comment by ObjectJosh** [comment]
@jmanhype Did you do a fresh install?

**Comment by ObjectJosh** [comment]
@jmanhype Ping me on the discord, I'll try to help!

**Comment by jmanhype** [comment]
Whats your discord?

**Comment by ObjectJosh** [comment]
@jmanhype Here's our discord: https://discord.gg/p5YpZ5vjd9

**Comment by jmanhype** [comment]
I retract my HYPE statement its working. 

Was a skill error on my part. 

what got it working for me was, the workspace directory had a space in the name, which was causing the error. 

Make sure your workspace dir has 0 spaces.

**Comment by ObjectJosh** [comment]
@jmanhype ayy let's go! Noted. Feel free to create a new issue for this and I'll make sure it gets fixed :)
