### ISSUE TITLE
Can not start devon

### ISSUE THREAD

**Issue by zhlmmc** [entropy-research/Devon#79]
![image](https://github.com/entropy-research/Devon/assets/1726527/66b5deba-60c6-401a-97db-e8e786c7a54f)

And the terminal says:
npx devon-ui
Encryption is available and can be used.
/Users/zhlmmc/Library/Application Support/Electron
[27206:0629/185721.020328:ERROR:network_service_instance_impl.cc(600)] Network service crashed, restarting service.

**Comment by maishathasin** [comment]
yea I also have this issue

**Comment by akiradev0x** [comment]
You need to install the backend with pipx! @zhlmmc @maishathasin
