### ISSUE TITLE
UI problem

### ISSUE THREAD

**Issue by hustnn** [entropy-research/Devon#89]
It looks like the UI is not working properly, feel like the window is not allowed to popup and the files in the folder are not shown.

<img width="210" alt="image" src="https://github.com/entropy-research/Devon/assets/73186/99de0b19-ac66-4d4a-8350-a34dd22551b2">

I can also input anything in the terminal, it is frozen. 
<img width="584" alt="image" src="https://github.com/entropy-research/Devon/assets/73186/929cf83d-b7d2-471b-a3ba-5776389443d5">

**Comment by ObjectJosh** [comment]
What do you mean by window is not allowed to pop up? What does it say in the console when you open devtools?

**Comment by hustnn** [comment]
for the devtools, do you mean this?

<img width="1177" alt="image" src="https://github.com/entropy-research/Devon/assets/73186/a47e1dbf-624a-4b15-b8bf-a23094da58a9">

**Comment by ObjectJosh** [comment]
Did you open an empty directory? Also the terminal is read-only.

**Comment by hustnn** [comment]
> Did you open an empty directory? Also the terminal is read-only.

correct. the whole edit window looks like can not been selected such as terminal, min/max button.

**Comment by ObjectJosh** [comment]
Since it's an empty directory, there are no files shown. The stoplight buttons are for aesthetic purposes only so they're not intended to work

**Comment by hustnn** [comment]
> Since it's an empty directory, there are no files shown. The stoplight buttons are for aesthetic purposes only so they're not intended to work

The Devon directory has files inside, I am just open the Devon itself. How about the terminal, is it readonly also?

**Comment by ObjectJosh** [comment]
As mentioned before, the terminal is read only

**Comment by hustnn** [comment]
> As mentioned before, the terminal is read only

ok, then just cannot see the files in the folder, Devon is working for programming task, just want to make the UI to show the files and I can browse and select them for better experience.

**Comment by hustnn** [comment]
Is there any feature on the edit like select the part of the code to let devon refine it or just browsing purpose. If just for browsing, I can open them in vscode as well.

**Comment by ObjectJosh** [comment]
Hm, interesting. Haven't seen this issue before, if the directory *isn't* empty and the files aren't loading in. So everything's working except the editor? *Maybe* it's a permissions issue with parcel watcher? https://github.com/entropy-research/Devon/blob/main/electron/src/backend/plugins/editor.ts
But interesting I don't see any logs in console

**Comment by hustnn** [comment]
> permissions issue

Is it related to my mac permission setting?

**Comment by ObjectJosh** [comment]
I'm not too sure, since I don't see any useful logs and haven't run into this issue. If you'd like to debug further you may need to run it locally.

**Comment by hustnn** [comment]
I can run it locally via `npm start`,  do you know how to debug it?

**Comment by hustnn** [comment]
I met an issue when I installed it locally

I first install devon-agent with
`poetry install`

I had this issue when starting with `npm start`, does it mean my devon-agent is not installed correctly?
<img width="276" alt="image" src="https://github.com/entropy-research/Devon/assets/73186/d800662f-a574-4595-a616-690835f01feb">

**Comment by hustnn** [comment]
I figured it out 
<img width="510" alt="image" src="https://github.com/entropy-research/Devon/assets/73186/1a7ad1aa-6081-4621-9f01-73d289028091">
