### ISSUE TITLE
Error installing in windows 11

### ISSUE THREAD

**Issue by Jrmymlna** [entropy-research/Devon#94]
pipx install devon_agent
Fatal error from pip prevented installation. Full pip output in file:
    C:\Users\Jeremy\pipx\logs\cmd_2024-07-22_16.47.28_pip_errors.log

pip seemed to fail to build package:
    code-nav-devon<0.2.0,>=0.1.1

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    error: metadata-generation-failed

Error installing devon-agent.

**Comment by Jrmymlna** [comment]
i closed this issue because no one help me.. how cruel this world..

**Comment by ObjectJosh** [comment]
@Jrmymlna hey apologies for not seeing this earlier. We don't support Windows right now, however we had someone just yesterday on the discord who also got this error and was able to fix it I believe. Please join our [discord](https://discord.gg/p5YpZ5vjd9) and I'd be happy to try and help. Sorry about the inconvenience!
